# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               nmalacarne.awake?
tagline:             'do_code'
description:         'nicholas malacarne.'
url:                 http://nmalacarne.me
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Nicholas Malacarne
  url:               https://github.com/nmalacarne
  email:             nicholas.malacarne@gmail.com

# Custom vars
version:             1.0.0
